<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>httpspec</string>
	</array>
	<key>name</key>
	<string>HTTP Spec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>meta.request.httpspec</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#request</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^$</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#response</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ampersand</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\&amp;)\&amp;(?!\&amp;)</string>
					<key>name</key>
					<string>support.function.ampersand.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>closingbracket</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.other.multiplexend.httpspec</string>
					<key>match</key>
					<string>\]</string>
				</dict>
			</array>
		</dict>
		<key>comma</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\,</string>
					<key>name</key>
					<string>keyword.other.comma.httpspec.test</string>
				</dict>
			</array>
		</dict>
		<key>emptyline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*$</string>
				</dict>
			</array>
		</dict>
		<key>equals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\=</string>
					<key>name</key>
					<string>support.function.keyvaluepairseparator.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>header</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.headername.httpspec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^([^()&lt;&gt;@,;:\\"{} \t\x00-\x1F\x7F]+\:)\s(.*)$</string>
					<key>name</key>
					<string>string.unquoted.uri.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>invalidcomma</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\,|\,(?=\s)</string>
					<key>name</key>
					<string>invalid.illegal.comma.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>jsonblock</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
		<key>methodlist</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#methodname</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalidcomma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>methodname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:\b)(OPTIONS|HEAD|GET|DELETE|PUT|PATCH|POST)</string>
					<key>name</key>
					<string>keyword.other.method.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>multiplex</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#uripart</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>namevaluepair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#uriqueryname</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#equals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uriqueryvalue</string>
				</dict>
			</array>
		</dict>
		<key>openingbracket</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>keyword.other.multiplexstart.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>questionmark</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>support.function.queryseparator.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>request</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=ACL|BASELINE-CONTROL|BIND|CHECKIN|CHECKOUT|CONNECT|COPY|DELETE|GET|HEAD|LABEL|LINK|LOCK|MERGE|MKACTIVITY|MKCALENDAR|MKCOL|MKREDIRECTREF|MKWORKSPACE|MOVE|OPTIONS|ORDERPATCH|PATCH|POST|PRI|PROPFIND|PROPPATCH|PUT|REBIND|REPORT|SEARCH|TRACE|UNBIND|UNCHECKOUT|UNLINK|UNLOCK|UPDATE|UPDATEREDIRECTREF|VERSION-CONTROL
)</string>
					<key>end</key>
					<string>^(?=\d\d\d|HTTP)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#requestline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#header</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#jsonblock</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>requestline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#methodlist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uri</string>
				</dict>
			</array>
		</dict>
		<key>response</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#statusline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#jsonblock</string>
				</dict>
			</array>
		</dict>
		<key>statusline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.statustext.httpspec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\d\d\d)\s(.*)$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.statustext.httpspec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^HTTP/(1\.1|2|3)\s(\d\d\d)\s(.*)$</string>
				</dict>
			</array>
		</dict>
		<key>uri</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#uriabsolute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uripath</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiplex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#questionmark</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#uriquery</string>
				</dict>
			</array>
		</dict>
		<key>uriabsolute</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:\s)(https?):\/\/((?:(?:[A-Za-z0-9\-]{1,63})\.)*(?:[A-Za-z0-9\-]{1,63}))</string>
					<key>end</key>
					<string>(?:$)</string>
					<key>name</key>
					<string>support.function.httpspec</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#uripart</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#multiplex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>uripart</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-bA-B0-9\-_/]+)</string>
				</dict>
			</array>
		</dict>
		<key>uripath</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?:\s)\/</string>
					<key>end</key>
					<string>(?:$)</string>
					<key>name</key>
					<string>support.function.httpspec</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#uripart</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#multiplex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>uriquery</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#namevaluepair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
			</array>
		</dict>
		<key>uriqueryname</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[?&amp;])([^=&amp;])+</string>
					<key>name</key>
					<string>support.function.uriqueryname.httpspec</string>
				</dict>
			</array>
		</dict>
		<key>uriqueryvalue</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\=)([^=&amp;]+)</string>
					<key>name</key>
					<string>support.function.uriqueryvalue.httpspec</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.httpspec</string>
	<key>uuid</key>
	<string>7bb6ff35-8b8a-4480-91ec-20f2d3fcba9a</string>
</dict>
</plist>